<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '<b>{message}</b><br />tiedostossa <i>{file}</i> rivillä <i>{line}</i>.<br/>-- {link}',
    'Action' => 'Toiminto',
    'Args' => 'Argumentit',
    'Audit' => 'Audit',
    'Audit Error in Audit Entry #{entry_id}' => 'Audit-virhe merkinnässä #{entry_id}',
    'Audit Module' => 'Audit-moduuli',
    'BCC' => 'Piilokopio',
    'CC' => 'Kopio',
    'Called' => 'Kutsuttu',
    'Content' => 'Sisältö',
    'Content - HTML' => 'HTML -sisältö',
    'Content - JSON' => 'JSON -sisältö',
    'Content - Query' => 'Tiedustelu -sisältö',
    'Content - XML' => 'XML -sisältö',
    'Created' => 'Luotu',
    'Data' => 'Tieto',
    'Diff' => 'Ero',
    'Difference' => 'Ero',
    'Download' => 'Lataa',
    'Download eml file' => 'Lataa eml-tiedosto',
    'Duration' => 'Kesto',
    'Emailed' => 'Sähköposti lähetetty',
    'Entries' => 'Merkinnät',
    'Entry #{id}' => 'Merkintä #{id}',
    'Entry ID' => 'Merkintätunnus',
    'Error #{id}' => 'Virhe #{id}',
    'Error Code' => 'Virhekoodi',
    'Errors' => 'Virheet',
    'Extra Data' => 'Lisätiedot',
    'Field' => 'Kenttä',
    'Field ID-:id' => 'Kenttä ID-:id',
    'Fields' => 'Kentät',
    'File' => 'Tiedosto',
    'From' => 'Lähettäjä',
    'Guest' => 'Vieras',
    'HTML' => 'HTML',
    'HTML Body' => 'HTML-runko',
    'Hash' => 'Hash',
    'Headers' => 'Header-kentät',
    'ID' => 'ID',
    'IP' => 'IP',
    'Info' => 'Info',
    'Javascript #{id}' => 'Javascript #{id}',
    'Javascripts' => 'Javascriptit',
    'Line' => 'Rivi',
    'Log' => 'Loki',
    'Mail #{id}' => 'Sähköposti #{id}',
    'Mails' => 'Sähköpostit',
    'Memory' => 'Muisti',
    'Message' => 'Viesti',
    'Model ID' => 'Mallin tunnus',
    'New Value' => 'Uusi arvo',
    'No' => 'Ei',
    'Old Value' => 'Vanha arvo',
    'Origin' => 'Alkuperä',
    'POST' => 'POST',
    'POST - HTML' => 'POST - HTML',
    'POST - JSON' => 'POST - JSON',
    'POST - Query' => 'POST - Query',
    'POST - XML' => 'POST - XML',
    'Profiling' => 'Profilointi',
    'Reply' => 'Vastaus',
    'Request' => 'Pyyntö',
    'Request #{id}' => 'Pyyntö #{id}',
    'Request Method' => 'Pyyntömenetelmä',
    'Reset Filters' => 'Nollaa suodattimet',
    'Result' => 'Tulos',
    'Result - Object' => 'Tulos - Objekti',
    'Result - XML' => 'Tulos - XML',
    'SOAP' => 'SOAP',
    'Search' => 'Haku',
    'Stack Trace' => 'Jäljityspino',
    'Subject' => 'Aihe',
    'Successful' => 'Onnistunut',
    'Text' => 'Teksti',
    'Text Body' => 'Tekstirunko',
    'To' => 'Vastaanottaja',
    'Trace' => 'Jäljitys',
    'Trail #{id}' => 'Jälki #{id}',
    'Trails' => 'Jäljet',
    'Type' => 'Tyyppi',
    'User' => 'Käyttäjä',
    'User ID' => 'Käyttäjätunnus',
    'Yes' => 'Kyllä',
    'cURL' => 'cURL',
    'view audit entry' => 'Näytä merkintä',
    '{message}
in {file} on line {line}.
-- {url}' => '{message}
tiedostossa {file} rivillä {line}.
-- {url}',
];
